<?php


class greenbox
{
    const WHITE_CARDS = [
        ["text" => "_ be all like _.", "pick" => 2],
        ["text" => "Art isn\'t just a painting in a stuffy museum. Art is alive. Art is _.", "pick" => 1],
        ["text" => "As reparations for slavery, all African Americans will receive _.", "pick" => 1],
        [
            "text" => "As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and _.",
            "pick" => 1,
        ],
        [
            "text" => "Best you go back where you came from, now. We don\'t take too kindly to _ in these parts.",
            "pick" => 1,
        ],
        ["text" => "CNN breaking news! Scientists discover _.", "pick" => 1],
        ["text" => "Coming to Red Lobster&reg; this month, _.", "pick" => 1],
        [
            "text" => "Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you _.",
            "pick" => 1,
        ],
        [
            "text" => "Dance like there\'s nobody watching, love like you\'ll never be hurt, and live like you\'re _.",
            "pick" => 1,
        ],
        ["text" => "Errbody in the club _.", "pick" => 1],
        ["text" => "Feeling so grateful! #amazing #mylife #_.", "pick" => 1],
        ["text" => "Girls just wanna have _.", "pick" => 1],
        ["text" => "Google Calendar alert: _ in 10 minutes.", "pick" => 1],
        ["text" => "I don\'t believe in God. I believe in _.", "pick" => 1],
        ["text" => "I got rhythm, I\'ve got music, I\'ve got _. Who could ask for anything more?", "pick" => 1],
        ["text" => "I may not be much to look at, but I fuck like _.", "pick" => 1],
        ["text" => "I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like _.", "pick" => 1],
        ["text" => "I\'ll take the BBQ bacon burger with friend egg and fuck it how about _.", "pick" => 1],
        ["text" => "I\'m sorry, sir, but your insurance plan doesn\'t cover injuries caused by _.", "pick" => 1],
        [
            "text" => "I\'ve had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw _.",
            "pick" => 1,
        ],
        ["text" => "If at first you don\'t succeed, try _.", "pick" => 1],
        ["text" => "In the 1950s, psychologists prescribed _ as a cure for homosexually.", "pick" => 1],
        ["text" => "LSD + _ = really bad time.", "pick" => 1],
        ["text" => "\"Mom\'s to-do list:<br/>- Buy Groceries.<br/>- Clean up _.<br/>- Soccer Practice.\"", "pick" => 1],
        ["text" => "Most Americans would not vote for a candidate who is openly _.", "pick" => 1],
        ["text" => "No, no, no, no, no, no, NO! I will NOT let _ ruin this wedding.", "pick" => 1],
        ["text" => "Oh no! Siri, how do I fix _?", "pick" => 1],
        ["text" => "One more thing. Watch out for Big Mike. They say he killed a man with _.", "pick" => 1],
        ["text" => "Ooo, daddy like _.", "pick" => 1],
        ["text" => "Poor Brandon, still living in his parent\'s basement. I heard he never got over _.", "pick" => 1],
        ["text" => "Run, run, as fast as you can! You can\'t catch me, I\'m _!", "pick" => 1],
        ["text" => "She\'s a lady in the streets, _ in the sheets.", "pick" => 1],
        ["text" => "She\'s just one of the guys, you know? She likes beer, and football, and _.", "pick" => 1],
        [
            "text" => "Son, take it from someone who\'s been around the block a few times. Nothin\' puts her in the mood like _.",
            "pick" => 1,
        ],
        ["text" => "Summer lovin\', had me a blast. _, happened so fast.", "pick" => 1],
        [
            "text" => "\"The top Google auto-complete results for \"Barack Obama\":</br>- Barack Obama Height.</br>- Barack Obama net worth.</br>- Barack Obama _.\"",
            "pick" => 1,
        ],
        ["text" => "Then the princess kissed the frog, and all of a sudden the frog was _!", "pick" => 1],
        ["text" => "There is no God. It\'s just _ and then you die.", "pick" => 1],
        ["text" => "This Friday at the Liquid Lunge, it\'s _ Night! Ladies drink free.", "pick" => 1],
        ["text" => "We do not shake with our left hands in this country. That is the hand we use for _.", "pick" => 1],
        ["text" => "Well if _ is a crime, then lock me up!", "pick" => 1],
        ["text" => "Well, shit. My eyes ain\'t so good, but I\'ll eat my own boot if that ain\'t _!", "pick" => 1],
        ["text" => "What are all those whales singing about?", "pick" => 1],
        ["text" => "What sucks balls?", "pick" => 1],
        ["text" => "What totally destroyed my asshole?", "pick" => 1],
        ["text" => "What turned me into a Republican?", "pick" => 1],
        ["text" => "What will end racism once and for all?", "pick" => 1],
        ["text" => "What\'s a total waste of Hillary Clinton\'s time?", "pick" => 1],
        ["text" => "What\'s about to take dance floor to the next level?", "pick" => 1],
        ["text" => "What\'s the gayest?", "pick" => 1],
        ["text" => "What\'s the most problematic?", "pick" => 1],
        ["text" => "Why am I laughing and crying and taking off my clothes?", "pick" => 1],
        ["text" => "With a one-time gift of just $10, you can save this child from _.", "pick" => 1],
        ["text" => "You know who else liked _? Hitler.", "pick" => 1],
        ["text" => "You won\'t believe what\'s in my pussy. It\'s _.", "pick" => 1],
    ];

    const BLACK_CARDS = [
        ["text" => "10 football players with erections barreling towards you at full speed."],
        ["text" => "10,000 shrieking teenage girls."],
        ["text" => "A big ol\' plate of fettuccine alfredo."],
        ["text" => "A big, beautiful mouth packed to the brim with sparkling teeth."],
        ["text" => "A black friend."],
        ["text" => "A burrito that\'s just sour cream."],
        ["text" => "A cheerfulness that belies a deep-seated self-loathing."],
        ["text" => "A cold and indifferent universe."],
        ["text" => "A creature made of penises that must constantly arouse itself to survive."],
        ["text" => "A creepy child singing a nursery rhyme."],
        ["text" => "A dolphin that learns to talk and becomes the Dead of Harvard Law School."],
        ["text" => "A duffel bag full of lizards."],
        ["text" => "A finger up the butt."],
        ["text" => "A genetic predisposition for alcoholism."],
        ["text" => "A gun that shoots cobras."],
        ["text" => "A hug."],
        ["text" => "A long business meeting with no obvious purpose."],
        ["text" => "A man in a suit with perfect hair who tells you beautiful lies."],
        ["text" => "A man with the head of a goat and the body of a goat."],
        ["text" => "A massive collection of child pornography."],
        ["text" => "A medium horchata."],
        ["text" => "A negative body image that is totally justified."],
        ["text" => "A slowly encroaching circle of wolves."],
        ["text" => "A strong horse and enough rations for thirty days."],
        ["text" => "A terrified fat child who won\'t come out of the bushes."],
        ["text" => "A tiny fireman who puts out tiny fires."],
        ["text" => "A weird guy who says weird stuff and weirds me out."],
        ["text" => "A woman\'s right to choose."],
        ["text" => "A woman\'s perspective."],
        ["text" => "Aborting the shit out of a fetus."],
        ["text" => "Albert Einstein but if he had a huge muscles and a rhinoceros cock."],
        ["text" => "All these people I\'ve killed."],
        ["text" => "An arrangement wherein I give a person money they have sex with me."],
        ["text" => "An empowered woman."],
        ["text" => "An incurable homosexual."],
        ["text" => "An old dog full of tumors."],
        ["text" => "An older man."],
        ["text" => "An X-Man whose power is that he has sex with dogs and children."],
        ["text" => "Anal."],
        ["text" => "Antidepressants."],
        ["text" => "Art."],
        ["text" => "Assassinating the president."],
        ["text" => "Awesome pictures of planets and stuff."],
        ["text" => "Bad emotions I don\'t want."],
        ["text" => "Becoming the President of the United States."],
        ["text" => "Being sexually attracted to children."],
        ["text" => "Being turned into sausages."],
        ["text" => "Beyonc&eacute;."],
        ["text" => "Big, smart money boys tap-tapping on their keyboards."],
        ["text" => "Blossoming into a beautiful young woman."],
        ["text" => "Breastfeeding in public like a radiant earth goddess."],
        ["text" => "Brunch."],
        ["text" => "Catching a live salmon in your mouth."],
        ["text" => "Child labor."],
        ["text" => "China."],
        ["text" => "Chipotle."],
        ["text" => "Chris Hemsworth."],
        ["text" => "Comprehensive immigration reform."],
        ["text" => "Condoleezza Rice."],
        ["text" => "Consensual, nonreproductive incest."],
        ["text" => "Content."],
        ["text" => "Crazy anal orgasms."],
        ["text" => "Creamy slices of real, California avocado."],
        ["text" => "Critical thinking."],
        ["text" => "Crushing the patriarchy."],
        ["text" => "Daddy going away forever."],
        ["text" => "Defeating a gorilla in single combat."],
        ["text" => "Denying the Holocaust."],
        ["text" => "Dis bitch."],
        ["text" => "Discovering that what I really want in life is to kill people and have sex with their corpses."],
        ["text" => "Doing a somersault and barfing."],
        ["text" => "Dominating a man by peeing on his eldest son."],
        ["text" => "Doritos and a Fruit Roll-Up."],
        ["text" => "Dropping dead in a Sbarro\'s bathroom and not being found for 72 hours."],
        ["text" => "Dumpster juice."],
        ["text" => "Eating ass."],
        ["text" => "Eating people."],
        ["text" => "Eating too many Cinnabons and then vomiting and then eating the vomit."],
        ["text" => "Ejaculating at the apex of a cartwheel."],
        ["text" => "Esmeralda, my most beautiful daughter."],
        ["text" => "Eternal screaming madness."],
        ["text" => "Every man\'s ultimate fantasy: a perfectly cylindrical vagina."],
        ["text" => "Everything."],
        ["text" => "Exploring each other\'s buttholes."],
        ["text" => "Facilitating dialogue and deconstructing binaries."],
        ["text" => "Falling into a pit of waffles."],
        ["text" => "Farting a huge shit out of my pussy."],
        ["text" => "Farting all over my face with your tight little asshole."],
        ["text" => "Feeling the emotion of anger."],
        ["text" => "Feminism."],
        ["text" => "Film roles for actresses over 40."],
        ["text" => "Finding a nice elevator to poop in."],
        ["text" => "Forty-five minutes of finger blasting."],
        ["text" => "Founding a major world religion."],
        ["text" => "Fucking me good and taking me to Red Lobster&reg;."],
        ["text" => "Fucking my therapist."],
        ["text" => "Gary."],
        ["text" => "Gay thoughts."],
        ["text" => "Gayle from HR."],
        ["text" => "Gazpacho."],
        ["text" => "Getting aborted."],
        ["text" => "Getting blasted in the face by a t-shirt cannon."],
        ["text" => "Getting eaten out by a dog."],
        ["text" => "Getting high with mom."],
        ["text" => "Getting killed and dragged up a tree by a leopard."],
        ["text" => "Getting laid like all the time."],
        ["text" => "Getting naked too soon."],
        ["text" => "Getting pegged."],
        ["text" => "Getting the Dorito crumbs out of my purse."],
        ["text" => "Getting this party started!"],
        ["text" => "Getting trapped in a conversation about Ayn Rand."],
        ["text" => "Going around pulling people\'s tampons out."],
        ["text" => "Going to bed at a reasonable hour."],
        ["text" => "Gregor, my largest son."],
        ["text" => "Grunting for ten minutes and then peeing sand."],
        ["text" => "Guns."],
        ["text" => "Happy daddies with happy sandals."],
        ["text" => "Hating Jews."],
        ["text" => "Having a vagina."],
        ["text" => "Having an awesome time drinking and driving."],
        ["text" => "Having sex with a beautiful person."],
        ["text" => "Having sex with a man and then eating his head."],
        ["text" => "Having sex with your mom."],
        ["text" => "Holding the proper political beliefs of my time to attract a mate."],
        ["text" => "Homework."],
        ["text" => "Hot lettuce."],
        ["text" => "How good lead paint taste."],
        ["text" => "How great my ass looks in these jeans."],
        ["text" => "How sad it will be when Morgan Freeman dies."],
        ["text" => "How strange it is to be anything at all."],
        ["text" => "Huge big balls full of jizz."],
        ["text" => "Informing you that I am a registered sex offender."],
        ["text" => "ISIS."],
        ["text" => "It being too late to stop having sex with a horse."],
        ["text" => "Jason, the teen mayor."],
        ["text" => "Jazz."],
        ["text" => "Just now finding out about the Armenian Genocide."],
        ["text" => "Late-stage dementia."],
        ["text" => "Libertarians."],
        ["text" => "Loud, scary thunder."],
        ["text" => "Making out and stuff."],
        ["text" => "Math."],
        ["text" => "Meatloaf, the food."],
        ["text" => "Meatloaf, the man."],
        ["text" => "Menopause."],
        ["text" => "Mental illness."],
        ["text" => "Microaggressions."],
        ["text" => "Misogyny."],
        ["text" => "Mixing M&Ms and Skittles like some kind of psychopath."],
        ["text" => "Mommy and daddy fighting all the time."],
        ["text" => "Moon people."],
        ["text" => "Muchin\' puss."],
        ["text" => "My brother\'s hot friends."],
        ["text" => "My dog dying."],
        ["text" => "My huge penis and substantial fortune."],
        ["text" => "Objectifying women."],
        ["text" => "One of them big-city Jew lawyers."],
        ["text" => "One of those \"blow jobs\" I\'ve been hearing so much about."],
        ["text" => "Onions."],
        ["text" => "Opening your mouth to talk and a big penis fops out."],
        ["text" => "Our baby."],
        ["text" => "Out-of-control teenage blowjob parties."],
        ["text" => "Overthrowing the democratically-elected government of Chile."],
        ["text" => "Participating."],
        ["text" => "Period poops."],
        ["text" => "Picking up a glass of water and taking a sip and being the president."],
        ["text" => "Playing my asshole like a trumpet."],
        ["text" => "Plowing that ass like a New England corn farmer."],
        ["text" => "Political correctness."],
        ["text" => "Pooping in a leotard and hoping no one notices."],
        ["text" => "Pooping in the potty."],
        ["text" => "Prematurely ejaculating like a total loser."],
        ["text" => "Pretending to be one of the guys but actually being the spider god."],
        ["text" => "Putting more black people in jail."],
        ["text" => "Quacking like a duck in lieu of a cogent argument."],
        ["text" => "Quinoa."],
        ["text" => "Raising three kids on minimum wage."],
        ["text" => "Reaching an age where barbecue chips are better than sex."],
        ["text" => "Regurgitating a half-digested sparrow."],
        ["text" => "Restoring Germany to its former glory."],
        ["text" => "Rock-hard tits and a huge vagina."],
        ["text" => "Rolling so hard."],
        ["text" => "Rubbing my bush all over your bald head."],
        ["text" => "Salsa Night at Dave\'s Cantina."],
        ["text" => "Scissoring, if that\'s a thing."],
        ["text" => "Seizing control of the means of production."],
        ["text" => "Self-identifying as a DJ."],
        ["text" => "Showing all the boys my pussy."],
        ["text" => "Slamming a dunk."],
        ["text" => "Smashing my balls at the moment of climax."],
        ["text" => "Some of that good dick."],
        ["text" => "Some real spicy shrimps."],
        ["text" => "Starting a shitty podcast."],
        ["text" => "Straight blazin\' 24/7."],
        ["text" => "Sucking each other\'s penises for hours on end."],
        ["text" => "Sudden and unwanted slam poetry."],
        ["text" => "Swearing praise upon the Sultan\'s hideous daughters."],
        ["text" => "Systems and policies designed to preserve centuries-old power structures."],
        ["text" => "Tables."],
        ["text" => "Taking the form of a falcon."],
        ["text" => "Tender chunks of all-white-meat chicken."],
        ["text" => "That bitch, Stacy."],
        ["text" => "The amount of baby carrots I can fit up my ass."],
        ["text" => "The best, deepest quotes from The Dark Knight."],
        ["text" => "The body of a 46-year-old man."],
        ["text" => "The bond between a woman and her horse."],
        ["text" => "The chicken from Popeyes&reg;."],
        ["text" => "The clown that followed me home from the grocery store."],
        ["text" => "The fear and hatred in men\'s hearts."],
        ["text" => "The feeling of going to McDonald\'s as a 6-year-old."],
        ["text" => "The flaming wreckage of the International Space Station."],
        ["text" => "The full blown marginalization of ugly people."],
        ["text" => "The full force of the American military."],
        ["text" => "The government."],
        ["text" => "The graceful path of an autumn leaf as it falls to its earthen cradle."],
        ["text" => "The hottest MILF in Dallas."],
        ["text" => "The LGBT community."],
        ["text" => "The lived experience of African Americans."],
        ["text" => "The mysterious fog rolling into town."],
        ["text" => "The ol\' penis-in-the-popcorn surprise."],
        ["text" => "The Rwandan Genocide."],
        ["text" => "The secret to truly resilient hair."],
        ["text" => "The sweet, forbidden meat of the monkey."],
        ["text" => "The wind."],
        ["text" => "Thinking about what eating even is."],
        ["text" => "Three hours of nonstop penetration."],
        ["text" => "Tiny, rancid girl farts."],
        ["text" => "Trees."],
        ["text" => "Trevor, the world\'s greatest boyfriend."],
        ["text" => "Turning 32."],
        ["text" => "Twenty bucks."],
        ["text" => "Twenty cheerleaders laughing at your tiny penis."],
        ["text" => "Twisting my cock and balls into a balloon poodle."],
        ["text" => "Two beautiful pig sisters."],
        ["text" => "Two shitty kids and a garbage husband."],
        ["text" => "Waking up inside of a tornado."],
        ["text" => "Watching a hot person eat."],
        ["text" => "Watching you die."],
        ["text" => "Water."],
        ["text" => "When the big truck goes \"Toot! Toot!\""],
        ["text" => "Who really did 9/11."],
        ["text" => "Whomsoever let the dogs out."],
        ["text" => "Whooping your ass at Mario Kart."],
        ["text" => "Working so hard to have muscles and then having them."],
        ["text" => "You."],
    ];
}